---
title: "Stock Screener test V9"
author: "Yarden"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
# runtime: shiny
# params allow to later feed in new inputs, while rendering (or 'kniting')
params:
 data_file_name: 'NULL'
---


```{r comments_resources, include=FALSE}
# log scale plotting: ( scale_x_log10() )
# http://www.sthda.com/english/wiki/ggplot2-axis-scales-and-transformations
# http://docs.ggplot2.org/current/scale_continuous.html
# layout(p, xaxis = list(type = "log"),
#        yaxis = list(type = "log"))

# plot histogram with density
# http://r4stats.com/examples/graphics-ggplot2/

# plotly 3d???
# https://plot.ly/r/axes/#modifying-axes-for-3d-plots

# dynamically select x/y variables
# https://jjallaire.shinyapps.io/shiny-ggplot2-diamonds/

# some USEFUL crosstalk plotly examples
# https://github.com/jcheng5/plotly/tree/joe/feature/crosstalk/inst/examples/crosstalk

# crosstalk intro
# https://github.com/rstudio/crosstalk

# choose what vars to plot
# http://shiny.rstudio.com/articles/layout-guide.html

# plotly
# https://plot.ly/r/subplots/
# https://plot.ly/r/text-and-annotations/
# https://plot.ly/r/axes/

# running the app automatically:
# shiny::runApp('~/shinyapp')

# flexdashboard markdown layout
# http://rmarkdown.rstudio.com/flexdashboard/layouts.html#chart_stack_(scrolling)
# http://rmarkdown.rstudio.com/flexdashboard/examples.html
# https://jjallaire.shinyapps.io/shiny-biclust/

# knit when finished
# knitr::knit('plotly-report.Rmd', 'plotly-report.md')
# markdown::markdownToHTML('plotly-report.md', 'plotly-report.html')
# rmarkdown::run("crandash.Rmd")

```


<!-- # ```{r setup, echo=FALSE, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = FALSE) -->
<!-- ``` -->



```{r import, echo=FALSE}

library(dplyr)
library(crosstalk)
library(plotly)
library(DT)

# library(shiny)


#### Data set 1
try({
  work_dir <- 'C:/Users/Yarden-/Documents/Import plot stocks R script'
  setwd(work_dir)
})


# load data
stocks_raw <- readRDS(file = params$data_file_name)
# stocks_raw <- readRDS(file = 
#                         paste(work_dir, 'stocks_data.rds', sep = '/'))

# stocks_raw <- readRDS(file = data_file_name)
# stocks_raw <- readRDS(file = 'stocks_data_2.rds')

# set a earning indicator
stocks_raw$earning <- factor(stocks_raw$trailing_3_month_return > 0,
                             levels = c("TRUE", "FALSE"), 
                             labels = c('Earning', 'Not earning'))

stocks_Shared <- SharedData$new(stocks_raw)

```

Inputs {.sidebar data-width=700}
-----------------------------------------------------------------------
### Filters


```{r filter_sliders, echo=FALSE}

filter_slider("market_cap", 'Market Capitalization', stocks_Shared, ~market_cap)
filter_slider("net_profit_margin", 'Net profit margin', stocks_Shared, ~net_profit_margin)

filter_slider("price_to_book", 'Price / BV', stocks_Shared, ~price_to_book)
filter_slider("PE", 'PE', stocks_Shared, ~PE, step = 1)

filter_slider("bv_to_assets", 'BV / assets', stocks_Shared, ~bv_to_assets)
filter_slider("cur_assets_to_cur_liab", 'Current Assets / Current Liabilities', stocks_Shared, ~cur_assets_to_cur_liab)
filter_slider("return_this_month", 'Return This Month', stocks_Shared, ~return_this_month)
filter_slider("price_to_cashflow", 'Price / Cashflow', stocks_Shared, ~price_to_cashflow)
filter_slider("price_to_revenues", 'Price / Revenues', stocks_Shared, ~price_to_revenues)

# filter_slider("gross_margin", 'Gross margin', stocks_Shared, ~gross_margin)
# filter_slider("operating_margin", 'operating margin', stocks_Shared, ~operating_margin)

# filter_slider("ROE", 'ROE', stocks_Shared, ~ROE)
# filter_slider("ROA", 'ROA', stocks_Shared, ~ROA)
# filter_slider("trailing_3_month_return", 'Trailing 3 month return', stocks_Shared, ~trailing_3_month_return)

# selectInput('x', 'X', names(stocks_raw))
# selectInput('y', 'Y', names(stocks_raw), names(stocks_raw)[[2]])

# react_stocks_Shared <- reactive({
#   stocks_Shared$data()
# })

```


Row
-----------------------------------------------------------------------
### Scatter_1

```{r plot_scatter_1, echo=FALSE}

p1_scatter_1 <-
  plot_ly(stocks_Shared,
        x = ~market_cap,
        # paste the input as a formula
        # if input is NULL, hard-coded answer is market_cap
        # x = (function(x){as.formula(paste('~', if (is.null(x)) 'market_cap' else x,
        # sep = ''))})(input$x),
        y = ~net_profit_margin,
        # y = (function(x){as.formula(paste('~', if (is.null(x)) 'market_cap' else x,
        #                       sep = ''))})(input$y),
        text = rownames(stocks_Shared$data()),
  mode = "markers",
  # color = (function(x){x})(stocks_Shared$data()$earning),
  color = ~earning, 
  size = (function(x){500 * (x + 1) ** 1.1})(stocks_Shared$data()$gross_margin) ) %>%
  # size = ~gross_margin) %>%
  layout(dragmode = "select", 
         xaxis = list(showline = TRUE, zerolinecolor = TRUE, 
                      title = 'Market Cap (in millions, log scale)' ,type = "log"),
         yaxis = list(showline = TRUE, zerolinecolor = TRUE,
                      title = 'Net Profit Margin (in %)')) %>% 
  add_markers()
  # add_trace(mode = "markers") # %>%
  
(p1_scatter_1)


```

### Scatter_2

```{r plot_scatter_2, echo=FALSE}

p1_scatter_2 <-
  plot_ly(stocks_Shared,
        x = ~price_to_book,
        # paste the input as a formula
        # if input is NULL, hard-coded answer is market_cap
        # x = (function(x){as.formula(paste('~', if (is.null(x)) 'market_cap' else x,
        # sep = ''))})(input$x),
        y = ~PE,
        # y = (function(x){as.formula(paste('~', if (is.null(x)) 'market_cap' else x,
        #                       sep = ''))})(input$y),
        text = rownames(stocks_Shared$data()),
  mode = "markers",
  color = (function(x){as.formula(paste('~', x, sep = ''))})('price_to_cashflow'),
  size = (function(x){500 * (x + 1) ** 1.1})(stocks_Shared$data()$gross_margin)) %>%
  layout(dragmode = "select", 
         xaxis = list(showline = TRUE, zerolinecolor = TRUE, 
                      title = 'Price/BV'),
         yaxis = list(showline = TRUE, zerolinecolor = TRUE,
                      title = 'Price/Earnings')
         ) %>% 
  add_markers()
  # add_trace(mode = "markers") # %>%
  
(p1_scatter_2)


# text = ~paste('Country:', country, '<br>Life Expectancy:', lifeExp, '<br>GDP:', gdpPercap,
#                       '<br>Pop.:', pop)



```


Row {.tabset}
-----------------------------------------------------------------------
### Histogram

```{r plot_hist, echo=FALSE}

# p2_hist <- stocks_Shared %>%
#   plot_ly(x = ~earning, type = 'histogram',
#   color = I("black"), alpha = 0.5) %>%
#   
#   add_trace(x = stocks_Shared$origData()$earning, type = "histogram",
#   color = I("#377EB8")) %>%
#   layout(barmode="overlay", dragmode = "select",
#   showlegend = FALSE) # %>%

p2_hist <- stocks_Shared %>%
  plot_ly(alpha = 0.6) %>%
  add_histogram(x = ~stocks_Shared$data()$earning) %>%
  # add_histogram(x = ~stocks_Shared$origData()$earning) %>%
  layout(barmode = "overlay")
  
  # plot_ly(x = ~earning, type = 'histogram',
  # color = I("black"), alpha = 0.5) %>%
  # 
  # add_trace(x = stocks_Shared$origData()$earning, type = "histogram",
  # color = I("#377EB8")) %>%
  # layout(barmode="overlay", dragmode = "select",
  # showlegend = FALSE) # %>%

(p2_hist)

```


### Raw Data Table

```{r data_table, echo=FALSE}

p3_dt <- datatable(stocks_Shared)
          # rownames = as.character(iconv(rownames(stocks_Shared$data()),
          #                  from = "UTF-8", 
          #                  to = "UTF-8")))
(p3_dt)

```

